---
name: Release
on:
  workflow_run:
    types:
      - completed
    workflows:
      - "ci"
    branches:
      - release/*
jobs:
  print-debug-info:
    name: Print debug info for Release workflow
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v3

  get-tag:
    name: Get tag
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      tag: ${{ steps.get-tag-step.outputs.tag }}
    steps:
      - name: Get tag
        run: |
          branch=${{github.event.workflow_run.head_branch}}
          echo tag=${branch#release/} >> $GITHUB_OUTPUT
        id: get-tag-step

  create-release:
    name: Create release
    needs: get-tag
    uses: networkservicemesh/.github/.github/workflows/release.yaml@main
    secrets:
      token: ${{ secrets.BOT_TOKEN }}

  release-dependent-repositories:
    strategy:
      matrix:
        repository:
          - cmd-registry-k8s
    name: Update ${{ matrix.repository }}
    runs-on: ubuntu-latest
    needs: get-tag
    steps:
      - name: Create commit
        run: |
          echo "Update go.mod and go.sum to ${{ github.repository }}@${{ needs.get-tag.outputs.tag }}" >> /tmp/commit-message
      - name: Checkout bszirtes/${{ matrix.repository }}
        uses: actions/checkout@v4
        with:
          path: bszirtes/${{ matrix.repository }}
          repository: bszirtes/${{ matrix.repository }}
          token: ${{ secrets.BOT_TOKEN }}
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.3
      - name: Update ${{ matrix.repository }} locally
        working-directory: bszirtes/${{ matrix.repository }}
        continue-on-error: true
        run: |
          for dep in github.com/${{ github.repository }} \
                     github.com/bszirtes/sdk-k8s; do
            GOPRIVATE=github.com/bszirtes go get -u $dep@${{ needs.get-tag.outputs.tag }} || true
          done
          go mod tidy
          git diff
      - name: Push update to the ${{ matrix.repository }}
        working-directory: bszirtes/${{ matrix.repository }}
        run: |
          echo Starting to update repositotry ${{ matrix.repository }}
          git config --global user.email "nsmbot@networkservicmesh.io"
          git config --global user.name "NSMBot"
          git add go.mod go.sum
          git commit -s -F /tmp/commit-message
          git checkout -b ${{ github.event.workflow_run.head_branch }}
          git push -f origin ${{ github.event.workflow_run.head_branch }}
